### ISSUE TITLE
TODO Count 5/ FIXME Count 1

### ISSUE THREAD

**Issue by mandyvenables** [digitalbazaar/bedrock-vue-create-persona-wizard#8]
- [ ] TODO: specify propsData
       Commit: (8f44434) Add core files.
       File:  [test/web/10-Wizard.js:15](https://github.com/digitalbazaar/bedrock-vue-create-persona-wizard/blob/master/test/web/10-Wizard.js#L15)
       Dave Longley commented a year ago

  - [ ] TODO: consider moving to `bedrock-karma`?
       Commit: (8f44434) Add core files.
       File:  [test/test.config.js:12](https://github.com/digitalbazaar/bedrock-vue-create-persona-wizard/blob/master/test/test.config.js#L12)
       Dave Longley commented a year ago

  - [ ] FIXME: make configurable
       Commit: (8f44434) Add core files.
       File: [test/components/index.js:10](https://github.com/digitalbazaar/bedrock-vue-create-persona-wizard/blob/master/test/components/index.js#L10)
       Dave Longley commented a year ago

  - [ ] TODO: Move to bedrock-web-forms
       Commit: (82d9f3c) Complete initial wizard.
       File:  [BrPersonaNameForm.vue:54](https://github.com/digitalbazaar/bedrock-vue-create-persona-wizard/blob/master/BrPersonaNameForm.vue#L54)
       Ganesh Annan commented a year ago

  - [ ] TODO: Move to bedrock-web-forms
       Commit: (82d9f3c) Complete initial wizard.
       File: [BrPersonaDetailsForm.vue:69](https://github.com/digitalbazaar/bedrock-vue-create-persona-wizard/blob/master/BrPersonaDetailsForm.vue#L69)
       Ganesh Annan commented a year ago

  - [ ] TODO: $vm.el.something
       Commit: (8f44434) Add core files.
       File:  [test/web/10-Wizard.js:19](https://github.com/digitalbazaar/bedrock-vue-create-persona-wizard/blob/master/test/web/10-Wizard.js#L19)
       Dave Longley commented a year ago

       TODO Count          5
       FIXME Count         1
       Oldest Comment      a year ago
       Oldest Commenter    Dave Longley
       Oldest Comment      TODO: specify propsData
